version: '3.8'

services:
  app:
    container_name: app
    volumes:
      - ./app:/app
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
